### ISSUE TITLE
Standart Iconset in der parameters.yml definieren

### ISSUE THREAD

**Issue by heimseiten** [contao-themes-net/font-awesome-inserttag-bundle#3]
Vielen Dank für diese großartige Erweiterung!!!

Freue mich schon, wenn die Pro Icons für die svg sprites funktionieren.

Wenn ich es richtig sehe, wird, wenn nur bspw. {{fa::phone}} angegeben ist, das solid Iconpack verwendet. Es wäre toll, wenn man in der parameters.yml noch einstellen könnte, welches Iconset verwendet werden soll, wenn nur fa angegeben wird.

**Comment by MDevster** [comment]
Ja, kommt bestimmt Morgen, der PR muss nur noch geprüft werden ;)
https://github.com/contao-themes-net/font-awesome-inserttag-bundle/pull/2

**Comment by MDevster** [comment]
Feature added in version 1.1.1.
